build:
  version: "3.0"

cards:
  message: "Welcome to ecommerce products related local APIs default"
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "dragos@ecommerce.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932
