build:
  version: "3.0"

products:
  message: "Welcome to ecommerce accounts related products dev docker APIs"
  contactDetails:
    name: "John Doe - Developer1"
    email: "john@ecommerce.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
